### ISSUE TITLE
Missing characters in Lucene query syntax reserved chars regex.

### ISSUE THREAD

**Issue by LedzZm** [makinacorpus/php-lucene-query#4]
:wave:

In AbstractQuery.php the 'RE_SPECIALS' regular expression is missing some chars from [the spec](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters). Specifically, I don't see the '= <> /'

Should we change that to the following, or am I missing/misunderstanding something?

`/\+|-|&|\||!|\(|\)|\{|\}|\[|\]|\^|"|~|\*|\?|\:|\\\/`
to
`/\+|-|=|&|\||<|>|!|\(|\)|\{|\}|\[|\]|\^|"|~|\*|\?|\:|\/|\\\/`

Cheers!

**Comment by pounard** [comment]
To be honest, this code is more than 10 years old ! If I remember correctly this regex was copy/pasted from some Apache documentation at the time, its possible that it's wrong, feel free to propose a patch along with some unit tests !

**Comment by LedzZm** [comment]
I made the discussed addition and created some assertions for those cases. 
If there is anything you would like differently, let me know.

**Comment by pounard** [comment]
I'll look at this next week I hope, I'm sorry life being life I've had a lot on my plate those last few month.

**Comment by pounard** [comment]
I merged it manually, I cleaned up unit tests, thanks a lot.
