### ISSUE TITLE
[Documentation] How to use createCollection correctly

### ISSUE THREAD

**Issue by ArielZamparini-REISys** [makinacorpus/php-lucene-query#7]
I have an issue with figuring out the syntax to make a complicated query possible.

Lets say I have 3 text fields and a couple of checkboxes. How do I combine these two sections together. 

I want to have it do something like:
Field 1 = abc
AND field 2 = 123
AND (field 3 = a OR field 3 = b)

$queryBuilder = new Query();
// All individual filters are ANDed together
$queryBuilder->setOperator(Query::OP_AND);
$queryBuilder->matchTerm('field 1', 'abc');
$queryBuilder->matchTerm('field 2', '123');

// THE PART THAT DOESNT WORK Grouped filters
$queryBuilder
        ->createCollection(Query::OP_OR);
foreach ($terms as $key) {
  $queryBuilder->add($queryBuilder->matchTerm('field 3', $key));
}

How would I fix this code to yield the proper query?

**Comment by pounard** [comment]
Hello, here is a way to write it, using the actual stable version:

```php
    public function testDocumentationIssue7Legacy()
    {
        $query = new Query();
        $query->setOperator(Query::OP_AND);

        $query->createTerm()->setField('field 1')->setValue('abc');
        $query->createTerm()->setField('field 2')->setValue(123);

        $query
            ->createTermCollection(Query::OP_OR)
            ->add(
                (new TermQuery())
                    ->setField('field 3')
                    ->setValue('a')
            )
            ->add(
                (new TermQuery())
                    ->setField('field 3')
                    ->setValue('b')
            )
        ;

        self::assertSame(
            '("field 1":abc AND "field 2":123 AND ("field 3":a OR "field 3":b))',
            \trim((string) $query)
        );
    }
```

This is a unit test because I added it while resolving your problem.

Now, I did a minor refactor, allowing to shortcut it this way:

```php
    public function testDocumentationIssue7()
    {
        $query = new Query();
        $query->setOperator(Query::OP_AND);

        $query->createTerm()->setField('field 1')->setValue('abc');
        $query->createTerm()->setField('field 2')->setValue(123);

        $or = $query->createTermCollection(Query::OP_OR);
        $or->createTerm()->setField('field 3')->setValue('a');
        $or->createTerm()->setField('field 3')->setValue('b');

        self::assertSame(
            '("field 1":abc AND "field 2":123 AND ("field 3":a OR "field 3":b))',
            \trim((string) $query)
        );
    }
```

This new method will only be available in next release.

**Comment by pounard** [comment]
Does it answer your question ?

**Comment by ArielZamparini-REISys** [comment]
Yes! thanks for the assistance

**Comment by pounard** [comment]
<del>I guess I did something really wrong with my refactor, I'm going to fix that. It's been a long time I didn't work with this project, and I forgot some constraints...</del>

**Comment by pounard** [comment]
Forget my previous comment, here is an alternative also working syntax:

```php
    public function testDocumentationIssue7Best()
    {
        $query = new Query();
        $query->setOperator(Query::OP_AND);

        $query->createTerm()->setField('field 1')->setValue('abc');
        $query->createTerm()->setField('field 2')->setValue(123);

        $or = $query->createTermCollection(Query::OP_OR);
        $or->setField("field 3");
        $or->createTerm()->setValue('a');
        $or->createTerm()->setValue('b');

        self::assertSame(
            '("field 1":abc AND "field 2":123 AND "field 3":(a OR b))',
            \trim((string) $query)
        );
    }
```

**Comment by pounard** [comment]
Please note that I didn't used a Lucene query-able index, so I'm not sure that generated queries will work as expected, I'd suggest you to conduct some functional tests on your side.
