### ISSUE TITLE
 PHP Parse error:  syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\\\ (T_NS_SEPARATOR)

### ISSUE THREAD

**Issue by quantrpeter** [makinacorpus/php-lucene-query#8]
hi, please help

 PHP Parse error:  syntax error, unexpected 'new' (T_NEW), expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST) or \\\\ (T_NS_SEPARATOR)

for this line:

use new MakinaCorpus\Lucene\Query;

**Comment by pounard** [comment]
Oups I must have created a release with a typo error accidentitally... I will fix this within the next week.

**Comment by pounard** [comment]
There was a very old typo in documentation, fixed it, but code is working fine.
