### ISSUE TITLE
Undefined constant MakinaCorpus\Lucene\CollectionQuery::OP_REQUIRE

### ISSUE THREAD

**Issue by deevus** [makinacorpus/php-lucene-query#9]
Since 9ed20290de24cd7af05b4d465813be5541422067 we've been getting the following errors:

In my editor:
![image](https://user-images.githubusercontent.com/856194/216187138-5ab31f4e-adbc-4222-9ae2-54c5606839f2.png)

In production:
<img width="845" alt="image" src="https://user-images.githubusercontent.com/856194/216187362-c7abfa16-233a-49b4-b0e6-dd28d5e9dee1.png">

I'm fairly sure it is because `CollectionQuery` does not define these constants and they are defined in `Query` which extends `CollectionQuery`

**Comment by pounard** [comment]
Ouch, sad error, I'll fix this ASAP, sorry.

**Comment by pounard** [comment]
Fixed, added a few tests, and released in the 1.2.1 version. Thanks for reporting.
